name: Deploy Kanban Stack

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: self-hosted
    environment:
      name: ${{ github.ref == 'refs/heads/main' && 'production'}}

    env:
      COMPOSE_PROJECT_NAME: ${{ github.ref == 'refs/heads/main' && 'kanban-prod'}}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Deploy and Sync
        run: |
          # 1. Configurações de diretório
          mkdir -p ~/.ssh
          ssh-keyscan github.com >> ~/.ssh/known_hosts 2>/dev/null
          cd "${{ vars.REMOTE_TARGET }}"

          # 2. Derruba stack atual
          docker compose -p $COMPOSE_PROJECT_NAME down --remove-orphans || true

          # 3. Sincronização
          git fetch origin ${{ github.ref_name }}
          git checkout -f ${{ github.ref_name }}
          git reset --hard origin/${{ github.ref_name }}

          # 4. Gerar .env
          echo "⚙️ Gerando arquivo .env..."
          cat > .env << EOF
          SPRING_DATASOURCE_URL=${{ secrets.SPRING_DATASOURCE_URL }}
          SPRING_DATASOURCE_USERNAME=${{ secrets.SPRING_DATASOURCE_USERNAME }}
          SPRING_DATASOURCE_PASSWORD=${{ secrets.SPRING_DATASOURCE_PASSWORD }}
          DB_PORT=${{ secrets.DB_PORT }}

          JWT_SECRET=${{ secrets.JWT_SECRET }}
          SECURITY_USERNAME=${{ secrets.SECURITY_USERNAME }}
          SECURITY_PASSWORD=${{ secrets.SECURITY_PASSWORD }}

          GRAFANA_USER=${{ secrets.GRAFANA_USER }}
          GRAFANA_PASSWORD=${{ secrets.GRAFANA_PASSWORD }}

          APP1_PORT=${{ secrets.APP1_PORT }}
          APP2_PORT=${{ secrets.APP2_PORT }}
          REDIS_PORT=${{ secrets.REDIS_PORT }}
          RABBITMQ_PORT=${{ secrets.RABBITMQ_PORT }}
          RABBITMQ_MANAGEMENT_PORT=${{ secrets.RABBITMQ_MANAGEMENT_PORT }}

          LOKI_URL=${{ secrets.LOKI_URL }}
          LOKI_PORT=${{ secrets.LOKI_PORT }}
          GRAFANA_PORT=${{ secrets.GRAFANA_PORT }}
          NGINX_PORT=${{ secrets.NGINX_PORT }}
          EOF


          # 5. Build e Up
          echo "🐳 Iniciando Docker Compose ($COMPOSE_PROJECT_NAME)..."
          docker compose -p $COMPOSE_PROJECT_NAME build
          docker compose -p $COMPOSE_PROJECT_NAME up -d --remove-orphans

          echo "🚀 Stack ($COMPOSE_PROJECT_NAME) atualizada com sucesso!"
